### GET request to example server
POST http://localhost:9000/api/users/register
Content-Type: application/json

{
    "name": "firdaus",
    "email": "firdaus@a.com",
    "password": "password"
}

###
### GET request to example server
GET http://localhost:9000/api/products
Authorization: Bearer {{token}}
###
### GET request to example server
GET http://localhost:9000/api/products/1
Authorization: Bearer {{token}}
###